#!/bin/sh
ssh ubuntu@172.31.0.185<<EOF
    cd ~/Book-Store/
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install v12.0.0
    npm install
    npm install -g nodemon pm2
    sudo docker-compose up
    exit
EOF